# development baseURL
#baseURL = 'https://mazzelman.github.io/mazzelman/'
# production baseURL
baseURL = 'https://www.marcelepp.de/'
languageCode = 'de-DE'
title = 'Marcel Epp | Angehender Fachinformatiker in der Systemintegration'
theme = 'Terminal'
defaultContentLanguage = 'de'
relativeURLs = false
canonifyURLs = false

[languages]
  [languages.de]
      title = "Marcel Epp | Angehender Fachinformatiker in der Systemintegration"
      languageName = "Deutsch"
      weight = 1

    [languages.de.params]
      readMore = "Weiterlesen"
      newerPosts = "Neuere Beiträge"
      olderPosts = "Ältere Beiträge"
      missingContentMessage = "Seite nicht gefunden..."

    [languages.de.params.logo]
      logoText = "Marcel Epp"

    [languages.de.menu]
      [[languages.de.menu.main]]
        identifier = "about"
        name = "Über mich"
        url = "/ueber-mich"
        weight = 1
      [[languages.de.menu.main]]
        identifier = "legal"
        name = "Impressum"
        url = "/impressum"
        weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      fencedCodeBlocks = true

[params]
  # center theme with default width
  centerTheme = true