baseURL = 'https://mazzelman.github.io/mazzelman/'
languageCode = 'de-DE'
title = 'Marcel Epp | Angehender Fachinformatiker in der Systemintegration'
theme = 'Terminal'
defaultContentLanguage = 'de'
relativeURLs = true
canonifyURLs = false

[languages]
[languages.de]
  title = "Marcel Epp | Angehender Fachinformatiker in der Systemintegration"
  languageName = "Deutsch"
  weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      fencedCodeBlocks = true